const words = {
    eng: {
        liveTv: 'Live TV',
        movies: 'Movies',
        series: 'Series',
        settings: 'Settings',
        search: 'Search',
        all: 'All',
        favorites: 'Favorites',
        play: 'Play',
        watchTrailer: 'Watch Trailer',
        cancel: 'Cancel',
        exit: 'Exit',
        logOut: 'Log Out',
        changeLanguage: 'Change Language',
        similarMovies: 'Similar Movies',
        episodes: 'Episodes',
        favorite: 'Favorite',
        changeParentalCode: 'Change Parental Code',
        lockCategories: 'Lock Categories',
        useXTREAMCodeEpg: 'Use XTREAM code EPG',
        useTMDBApi: 'Use TMDB api',
        removeSubtitleBackground: 'Remove Subtitle Background',
        enterPin: 'Enter Pin',
        enterNewPin: 'Enter New Pin',
        confirmPin: 'Confirm Pin',
        wrongPin: 'Wrong Pin',
        confirmedNewPin: 'Confirmed New Pin',
        sort: 'Sort',
        menu: 'Menu',
        category: 'Category',
        liveCategories: 'Live Categories',
        movieCategories: 'Movie Categories',
        seriesCategories: 'Series Categories',
        season: 'Season',
        username: 'Username',
        password: 'Password',
        unFavorite: 'Unfavorite',
    },
    arm: {
        liveTv: 'Հեռուստասերիալներ',
        movies: 'Ֆիլմեր',
        series: 'Սերիալներ',
        settings: 'Կարգավորումներ',
        search: 'Որոնում',
        all: 'Բոլորը',
        favorites: 'Ֆավորիտներ',
        play: 'Սկսել',
        watchTrailer: 'Դիտել տրեյլերը',
        cancel: 'Չեղարկել',
        exit: 'Ելք',
        logOut: 'Դուրս գալ',
        changeLanguage: 'Փոխել լեզուն',
        similarMovies: 'Նմանատիպ ֆիլմեր',
        episodes: 'Էպիզոդներ',
        favorite: 'Ֆավորիտ',
        changeParentalCode: 'Փոխել ծնողական կոդը',
        lockCategories: 'Կատեգորիաների կոդավորում',
        useXTREAMCodeEpg: 'Օգտագործել XTREAM կոդ EPG',
        useTMDBApi: 'Օգտագործել TMDB api',
        removeSubtitleBackground: 'Հեռացնել ենթագրական եզրագնացումը',
        enterPin: 'Մուտքագրեք ծնողական կոդը',
        enterNewPin: 'Մուտքագրեք նոր ծնողական կոդը',
        confirmPin: 'Հաստատեք ծնողական կոդը',
        wrongPin: 'Անվավեր ծնողական կոդ',
        confirmedNewPin: 'Հաստատված նոր ծնողական կոդ',
        sort: 'Դասավորել',
        menu: 'Մենյու',
        category: 'Կատեգորիա',
        liveCategories: 'Հեռուստասերիալի կատեգորիաներ',
        movieCategories: 'Ֆիլմերի կատեգորիաներ',
        seriesCategories: 'Սերիալների կատեգորիաներ',
        season: 'Սեզոն',
        username: 'Օգտանուն',
        password: 'Գաղտնաբառ',
        unFavorite: 'Հեռացնել Ֆավորիտներից',
    },
    russian: {
        liveTv: 'Телевидение',
        movies: 'Фильмы',
        series: 'Сериалы',
        settings: 'Настройки',
        search: 'Поиск',
        all: 'Все',
        favorites: 'Избранное',
        play: 'Воспроизвести',
        watchTrailer: 'Смотреть трейлер',
        cancel: 'Отмена',
        exit: 'Выход',
        logOut: 'Выйти',
        changeLanguage: 'Сменить язык',
        similarMovies: 'Похожие фильмы',
        episodes: 'Эпизоды',
        favorite: 'Избранное',
        changeParentalCode: 'Сменить родительский код',
        lockCategories: 'Заблокировать категории',
        useXTREAMCodeEpg: 'Использовать XTREAM код EPG',
        useTMDBApi: 'Использовать TMDB api',
        removeSubtitleBackground: 'Убрать фон субтитров',
        enterPin: 'Введите пин-код',
        enterNewPin: 'Введите новый пин-код',
        confirmPin: 'Подтвердите пин-код',
        wrongPin: 'Неверный пин-код',
        confirmedNewPin: 'Подтвержден новый пин-код',
        sort: 'Сортировать',
        menu: 'Меню',
        category: 'Категория',
        liveCategories: 'Категории ТВ',
        movieCategories: 'Категории фильмов',
        seriesCategories: 'Категории сериалов',
        season: 'Сезон',
        username: 'Имя пользователя',
        password: 'Пароль',
        unFavorite: 'Удалить из избранного',
    },
    portuguese: {
        liveTv: 'TV ao vivo',
        movies: 'Filmes',
        series: 'Séries',
        settings: 'Configurações',
        search: 'Pesquisa',
        all: 'Todos',
        favorites: 'Favoritos',
        play: 'Jogar',
        watchTrailer: 'Assistir trailer',
        cancel: 'Cancelar',
        exit: 'Sair',
        logOut: 'Sair',
        changeLanguage: 'Mudar idioma',
        similarMovies: 'Filmes similares',
        episodes: 'Episódios',
        favorite: 'Favorito',
        changeParentalCode: 'Alterar código parental',
        lockCategories: 'Bloquear categorias',
        useXTREAMCodeEpg: 'Usar código XTREAM EPG',
        useTMDBApi: 'Usar TMDB api',
        removeSubtitleBackground: 'Remover fundo de legenda',
        enterPin: 'Digite o pin',
        enterNewPin: 'Digite o novo pin',
        confirmPin: 'Confirme o pin',
        wrongPin: 'Pin errado',
        confirmedNewPin: 'Pin novo confirmado',
        sort: 'Ordenar',
        menu: 'Cardápio',
        category: 'Categoria',
        liveCategories: 'Categorias ao vivo',
        movieCategories: 'Categorias de filmes',
        seriesCategories: 'Categorias de séries',
        season: 'Temporada',
        username: 'Nome de usuário',
        password: 'Senha',
        unFavorite: 'Desfavoritar',
    },
    spanish: {
        liveTv: 'TV en vivo',
        movies: 'Películas',
        series: 'Series',
        settings: 'Ajustes',
        search: 'Buscar',
        all: 'Todos',
        favorites: 'Favoritos',
        play: 'Jugar',
        watchTrailer: 'Ver trailer',
        cancel: 'Cancelar',
        exit: 'Salir',
        logOut: 'Cerrar sesión',
        changeLanguage: 'Cambiar idioma',
        similarMovies: 'Películas similares',
        episodes: 'Episodios',
        favorite: 'Favorito',
        changeParentalCode: 'Cambiar código parental',
        lockCategories: 'Bloquear categorías',
        useXTREAMCodeEpg: 'Usar código XTREAM EPG',
        useTMDBApi: 'Usar TMDB api',
        removeSubtitleBackground: 'Eliminar fondo de subtítulos',
        enterPin: 'Ingrese el pin',
        enterNewPin: 'Ingrese el nuevo pin',
        confirmPin: 'Confirmar pin',
        wrongPin: 'Pin incorrecto',
        confirmedNewPin: 'Pin nuevo confirmado',
        sort: 'Ordenar',
        menu: 'Menú',
        category: 'Categoría',
        liveCategories: 'Categorías en vivo',
        movieCategories: 'Categorías de películas',
        seriesCategories: 'Categorías de series',
        season: 'Temporada',
        username: 'Nombre de usuario',
        password: 'Contraseña',
        unFavorite: 'Desfavorito',
    },
    japanese: {
        liveTv: 'ライブテレビ',
        movies: '映画',
        series: 'シリーズ',
        settings: '設定',
        search: 'サーチ',
        all: 'すべて',
        favorites: 'お気に入り',
        play: '遊ぶ',
        watchTrailer: '予告編を見る',
        cancel: 'キャンセル',
        exit: '出口',
        logOut: 'ログアウト',
        changeLanguage: '言語を変更する',
        similarMovies: '似たような映画',
        episodes: 'エピソード',
        favorite: 'お気に入り',
        changeParentalCode: '親コードを変更する',
        lockCategories: 'カテゴリをロックする',
        useXTREAMCodeEpg: 'XTREAMコードEPGを使用する',
        useTMDBApi: 'TMDB apiを使用する',
        removeSubtitleBackground: '字幕の背景を削除する',
        enterPin: 'ピンを入力してください',
        enterNewPin: '新しいピンを入力してください',
        confirmPin: 'ピンを確認する',
        wrongPin: '間違ったピン',
        confirmedNewPin: '確認された新しいピン',
        sort: 'ソート',
        menu: 'メニュー',
        category: 'カテゴリー',
        liveCategories: 'ライブカテゴリ',
        movieCategories: '映画カテゴリ',
        seriesCategories: 'シリーズカテゴリ',
        season: '季節',
        username: 'ユーザー名',
        password: 'パスワード',
        unFavorite: 'お気に入りから削除',
    }
}

export default words;