const words = {
    eng: {
        liveTv: 'Live TV',
        movies: 'Movies',
        series: 'Series',
        settings: 'Settings',
        search: 'Search',
        all: 'All',
        favorites: 'Favorites',
        play: 'Play',
        watchTrailer: 'Watch Trailer',
        cancel: 'Cancel',
        exit: 'Exit',
        logOut: 'Log Out',
        changeLanguage: 'Change Language',
    },
    arm: {
        liveTv: 'Հեռուստասերիալներ',
        movies: 'Ֆիլմեր',
        series: 'Սերիալներ',
        settings: 'Կարգավորումներ',
        search: 'Որոնում',
        all: 'Բոլորը',
        favorites: 'Ֆավորիտներ',
        play: 'Սկսել',
        watchTrailer: 'Դիտել տրեյլերը',
        cancel: 'Չեղարկել',
        exit: 'Ելք',
        logOut: 'Դուրս գալ',
        changeLanguage: 'Փոխել լեզուն',
    },
    russian: {
        liveTv: 'Телевидение',
        movies: 'Фильмы',
        series: 'Сериалы',
        settings: 'Настройки',
        search: 'Поиск',
        all: 'Все',
        favorites: 'Избранное',
        play: 'Воспроизвести',
        watchTrailer: 'Смотреть трейлер',
        cancel: 'Отмена',
        exit: 'Выход',
        logOut: 'Выйти',
        changeLanguage: 'Сменить язык',
    },
    portuguese: {
        liveTv: 'TV ao vivo',
        movies: 'Filmes',
        series: 'Séries',
        settings: 'Configurações',
        search: 'Pesquisa',
        all: 'Todos',
        favorites: 'Favoritos',
        play: 'Jogar',
        watchTrailer: 'Assistir trailer',
        cancel: 'Cancelar',
        exit: 'Sair',
        logOut: 'Sair',
        changeLanguage: 'Mudar idioma',
    }
}

export default words;